server.port=8087
spring.application.name=vet-pedidos

# Configuración de base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/vet_pedidos_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Puertos
catalogo.service.url=http://localhost:8082
duenio.service.url=http://localhost:8083
pago.service.url=http://localhost:8086
bodega.service.url=http://localhost:8091