# microservicio-catalogo-vet
#
# Microservicio de catálogo: gestiona Categorías y Productos de la Veterinaria.
# Los otros microservicios (carrito, pedidos) consultan este
# servicio por HTTP cuando necesitan información de un producto.
# Crear BD "vet_catalogo_db" en tu gestor de base de datos antes de arrancar.

server.port=8082
spring.application.name=vet-catalogo

# Configuración de base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/vet_catalogo_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
